# ScikitLearn의 성능 지표 함수들

In [9]:
import numpy as np
from sklearn.metrics import confusion_matrix, precision_score, recall_score, accuracy_score, f1_score

In [10]:
target = np.array([0] * 10 + [1] * 10)
print(target)
pred = np.array([0,0,0,0,0,1,1,1,0,0,1,1,1,1,1,1,0,0,1,1])
print(pred)

[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 1 1 1 0 0 1 1 1 1 1 1 0 0 1 1]


In [11]:
# 0 데이터 중 0으로 판단한 데이터 7개, 1로 판단한 데이터 3개
# 1 데이터 중 1으로 판단한 데이터 8개, 1로 판단한 데이터 2개
confusion_matrix(target, pred)

array([[7, 3],
       [2, 8]])

In [12]:
print("정밀도 :", precision_score(target, pred))
print("재현율 :", recall_score(target, pred))
print("정확도 :", accuracy_score(target, pred))
print("F1 점수 :", f1_score(target, pred))

정밀도 : 0.7272727272727273
재현율 : 0.8
정확도 : 0.75
F1 점수 : 0.7619047619047619
